### ISSUE TITLE
EffTeleport (2 errors)

### ISSUE THREAD

**Issue by AleNobek123** [Matocolotoe/Skript-1.8#28] opened 2021-03-26 12:46 UTC
1.
Could not pass event PlayerCommandPreprocessEvent to Skript v2.5.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
	at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
	at ch.njol.skript.lang.function.Function.execute(Function.java:135) ~[?:?]
	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265) ~[?:?]
	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:248) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 17 more
[13:40:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tp' in plugin Skript v2.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
	at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
	at ch.njol.skript.lang.function.Function.execute(Function.java:135) ~[?:?]
	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265) ~[?:?]
	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 15 more

2.
Could not pass event PlayerMoveEvent to Skript v2.5.3
java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
	at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

I'm using the latest version of Skript (1.8 version).

**Comment by Romitou** [comment] 2021-03-26 12:48
Duplicate of #16. Can you try with the [latest artifact](https://github.com/Matocolotoe/Skript-1.8/actions/runs/610387846) ?

**Comment by AleNobek123** [comment] 2021-03-26 12:52
All works fine, but now:

[13:51:00 ERROR]: [Skript] An error occurred while trying to enable support for WorldGuard 6. WorldGuard region support has been disabled!
[13:51:00 ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard

**Comment by Romitou** [comment] 2021-03-26 13:00
Unfortunately, the actions do not build the WorldGuard module. So I built it locally, can you confirm that [this version](https://cdn.discordapp.com/attachments/688331594209296433/824990860470648902/Skript.jar) works?

**Comment by AleNobek123** [comment] 2021-03-26 13:17
It works, thanks a lot! :D

**Closed as completed** 2021-03-26 13:18 UTC
Labels: duplicate
