### ISSUE TITLE
Spigot teleport bug

### ISSUE THREAD

**Issue by giqnt** [Matocolotoe/Skript-1.8#22] opened 2021-02-11 14:15 UTC
ok so im using spigot but in error log it says 'java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib' Lol
```
[23:13:48] [Server thread/ERROR]: Could not pass event EntityDamageEvent to Skript v2.5.3
java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
	at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at ch.njol.skript.bukkitutil.HealthUtils.damage(HealthUtils.java:81) [Skript.jar:?]
	at ch.njol.skript.bukkitutil.HealthUtils.heal(HealthUtils.java:92) [Skript.jar:?]
	at ch.njol.skript.effects.EffHealth.execute(EffHealth.java:120) [Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:51) [Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) [Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) [Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) [Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153) [Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111) [Skript.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [?:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Matocolotoe** [comment] 2021-02-11 15:20
Duplicate of #16

**Closed as completed** 2021-02-11 15:20 UTC
Labels: duplicate
